model:
  model_name: 'BinarySegmentation'
  class: "src.models.DeepLabV3Plus.DeepLabV3Plus"
  params:
    encoder_name: "mit_b5"
    num_classes: 1
    pretrained: true
    use_aux: false

dataset:
  splits:
    ratios:
      val: 0.05
      test: 0.05
    seed: 42
    method: "random"

  max_area: 1048576  #1024**2
  resize_mode: "crop"

  weights:
    AISegment: 1.0
    AM-2k: 1.0
    DIS5K: 1.0
    DUTS: 1.0
    HRS10K: 1.0
    HRSOD: 1.0
    MaSS13K: 1.0
    P3M-10k: 1.0
    ToonOut: 1.0
    UHRSD: 1.0

dataloader:
  batch_sizes:
    train: null
    val: null
    test: null
  shuffle:
    train: null
    val: null
    test: null

  seed: 42
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 2
  sampler:
    class: "src.data.WeightedDynamicBucketBatchSampler.WeightedDynamicBucketBatchSampler"
    params:
      base_batch_size: 8
      max_batch_size: 32
      min_batch_size: 1
      reference_area: 262144  #512**2
      replacement: True
      skip_overload_examples: True
      send_overload_report: True
  pad_collate:
    enabled: true
    alignment: 32
    pad_value: 0.0

learning:
  epochs: 100
  early_stopping_patience: 15
  accumulation_steps: 1
  use_pixels_accumulation: True
  pixels_per_step: 3e6
  use_fp16: True
  use_gradient_checkpointing: True
  compile_model: true
  compile_dynamic: true
  compile_options: "default"
  log_interval: 5
  save_criterion: "val/iou"
  mode: "max"
  use_cuda: True
  threshold: 0.5

  loss:
    class: "src.losses.ComboLoss.ComboLoss"
    params:
      weights: [ 0.1, 0.9 ]
      loss_functions:
        - class: "src.losses.FocalLoss.FocalLoss"
          params:
            alpha: 0.8
            gamma: 2.5
            reduction: 'mean'
            smooth: 1e-6

        - class: "src.losses.SoftDiceLoss.SoftDiceLoss"
          params: {}

  optimizer:
    class: "adam_mini.Adam_mini"
    params:
      lr: 1e-4
      weight_decay: 1e-4
      betas: [0.9, 0.999]
      eps: 1e-8
      dim: 512
      n_heads: 8
      model_sharding: false

  scheduler:
    class: "torch.optim.lr_scheduler.CosineAnnealingWarmRestarts"
    params:
      T_0: 10
      T_mult: 2
      eta_min: 1e-7

evaluating:
  metrics:
    - name: 'iou'
      class: "torchmetrics.JaccardIndex"
      params:
        task: 'binary'

    - name: 'accuracy'
      class: "torchmetrics.Accuracy"
      params:
        task: 'binary'

    - name: 'precision'
      class: "torchmetrics.Precision"
      params:
        task: 'binary'

    - name: 'recall'
      class: "torchmetrics.Recall"
      params:
        task: 'binary'

    - name: 'f1'
      class: "torchmetrics.F1Score"
      params:
        task: 'binary'

    - name: 'specificity'
      class: "torchmetrics.Specificity"
      params:
        task: 'binary'

    - name: 'mcc'
      class: "torchmetrics.MatthewsCorrCoef"
      params:
        task: 'binary'

logs:
  default:
    filename_pattern: "%Y%m%d_%H%M%S.log"
    use_colors: true
    console: true
    console_level: "INFO"
    file: true
    file_level: "DEBUG"
    max_bytes: 10485760
    backup_count: 5
    fmt: "[%(asctime)s.%(msecs)03d] - %(module)10s:%(lineno)-3d %(levelname)-7s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    encoding: 'utf-8'

  types:
    train:
      name: "segmentation_bg_train"
      filename_pattern: "train_%Y%m%d_%H%M%S.log"
      console_level: "INFO"
      file_level: "DEBUG"

    evaluate:
      name: "segmentation_bg_evaluate"
      filename_pattern: "evaluate_%Y%m%d_%H%M%S.log"
      console_level: "INFO"
      file_level: "INFO"

    data:
      name: "segmentation_bg_data"
      filename_pattern: "data_%Y%m%d_%H%M%S.log"
      console_level: "INFO"
      file_level: "INFO"