model:
  model_name: 'BinarySegmentation'
  class: "src.models.DeepLabV3Plus.DeepLabV3Plus"
  params:
    encoder_name: "mit_b5"
    num_classes: 1
    pretrained: true
    use_aux: false
    use_gradient_checkpointing: true
    group_norm_groups: 32
    group_norm_eps: 1e-5
    group_norm_preserve_weights: true


dataset:
  splits:
    ratios:
      val: 0.05
      test: 0.05
    seed: 42
    method: "random"

  max_area: 500000
  resize:
    train:
      mode: "mix-b"
      area_threshold_mix: 3000000
      min_foreground: 0.01
    test:
      mode: "resize"
    val:
      mode: "resize"

  weights:
    AISegment: 0.44
    AM-2k: 1.81
    DIS5K: 1.65
    DUTS: 0.79
    HRS10K: 0.81
    HRSOD: 1.62
    MaSS13K: 0.71
    P3M-10k: 0.81
    ToonOut: 1.31
    UHRSD: 1.05


dataloader:
  batch_sizes:
    train: null
    test: null
    val: null

  shuffle:
    train: null
    test: null
    val: null

  seed: 42
  num_workers: 8
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 4

  sampler:
    class: "src.data.WeightedDynamicBucketBatchSampler.WeightedDynamicBucketBatchSampler"
    params:
      max_batch_size: 32
      min_batch_size: 1
      max_load: 1000000
      replacement: true
      skip_overload_examples: true
      send_overload_report: true

  pad_collate:
    enabled: true
    alignment: 32
    pad_value: 0.0
    mode: "reflect"


learning:
  use_cuda: true
  epochs: 100
  early_stopping_patience: 15
  log_interval: 1
  save_criterion: "val/iou"
  mode: "max"
  threshold: 0.5
  use_fp16: true

  compile_model: false
  compile_dynamic: false
  compile_options: "reduce-overhead"

  accumulation_steps: 1
  use_pixels_accumulation: true
  pixels_per_step: 8000000


  loss:
    class: "src.losses.ComboLoss.ComboLoss"
    params:
      weights: [ 0.15, 0.85 ]
      loss_functions:
        - class: "src.losses.MaskedFocalLoss.MaskedFocalLoss"
          params:
            alpha: 0.6
            gamma: 2.5
            reduction: "mean"
            smooth: 1e-6

        - class: "src.losses.MaskedPixelwiseSoftDiceLoss.MaskedPixelwiseSoftDiceLoss"
          params: {}

  optimizer:
    class: "torch.optim.AdamW"
    params:
      lr: 1e-4
      weight_decay: 1e-4
      fused: true

  scheduler:
    class: "torch.optim.lr_scheduler.CosineAnnealingWarmRestarts"
    params:
      T_0: 10
      T_mult: 2
      eta_min: 1e-7


runtime:
  cuda_alloc:
    expandable_segments: false
    max_split_size_mb: 0
  nvml_check: true
  cudnn_cache_limit: -1
  allow_tf32: true
  torch_compile:
    disable_triton: false
    cpp_wrapper: false
    max_autotune: false


evaluating:
  metrics:
    - name: "iou"
      class: "torchmetrics.JaccardIndex"
      params:
        task: "binary"

    - name: "accuracy"
      class: "torchmetrics.Accuracy"
      params:
        task: "binary"

    - name: "precision"
      class: "torchmetrics.Precision"
      params:
        task: "binary"

    - name: "recall"
      class: "torchmetrics.Recall"
      params:
        task: "binary"

    - name: "f1"
      class: "torchmetrics.F1Score"
      params:
        task: "binary"

    - name: 'specificity'
      class: "torchmetrics.Specificity"
      params:
        task: 'binary'

    - name: 'mcc'
      class: "torchmetrics.MatthewsCorrCoef"
      params:
        task: 'binary'


logs:
  default:
    filename_pattern: "%Y%m%d_%H%M%S.log"
    use_colors: true
    console: true
    console_level: "INFO"
    file: true
    file_level: "DEBUG"
    max_bytes: 10485760
    backup_count: 5
    fmt: "[%(asctime)s.%(msecs)03d] - %(module)10s:%(lineno)-3d %(levelname)-7s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    encoding: 'utf-8'

  types:
    train:
      name: "segmentation_bg_train"
      filename_pattern: "train_%Y%m%d_%H%M%S.log"
      console_level: "INFO"
      file_level: "DEBUG"

    evaluate:
      name: "segmentation_bg_evaluate"
      filename_pattern: "evaluate_%Y%m%d_%H%M%S.log"
      console_level: "INFO"
      file_level: "INFO"

    data:
      name: "segmentation_bg_data"
      filename_pattern: "data_%Y%m%d_%H%M%S.log"
      console_level: "INFO"
      file_level: "INFO"