default:
  filename_pattern: "default.log"
  fmt: "[%(asctime)s.%(msecs)03d] - %(module)10s:%(lineno)-3d %(levelname)-7s - %(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"
  encoding: "utf-8"

  console:
    enable: true
    level: "INFO"
    use_colors: true

  file:
    enable: true
    level: "DEBUG"
    max_bytes: 10485760
    backup_count: 5

types:
  data:
    name: "data"
    filename_pattern: "data.log"
    console:
      level: "INFO"
    file:
      level: "DEBUG"

  learning:
    name: "learning"
    filename_pattern: "learning.log"
    console:
      level: "INFO"
    file:
      level: "DEBUG"

  evaluating:
    name: "evaluating"
    filename_pattern: "evaluating.log"
    console:
      level: "INFO"
    file:
      level: "DEBUG"
